version: '3.1'
services:
  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=server_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  stats-server:
    build: ./statistics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/server_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

